spring:
  application:
    name: mailServise
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}
        register: true
        register-health-check: false
        service-name: ${spring.application.name}
      host: localhost
      port: 8500
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: JCcccHost
  mqtt:
    username: guest
    password: guest
    url: tcp://127.0.0.1:1883
    client:
      id: mqttId
    default:
      topic: topic,topic1
    completionTimeout: 3000
  mail:
    host: smtp.gmail.com
    port: 465
    username: ksumatova178@gmail.com
    password: hayxdlobulrrcyop
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    protocol: smtps
  quartz:
    job-store-type: memory
